Fix deployment script: Use correct client.agent_engines.create() API
Moved global declaration to top of main() function to fix SyntaxError.
The global statement must appear before any usage of the variables.

Error fixed:
  SyntaxError: name 'PROJECT_ID' is used prior to global declaration